# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(
      task: "assemble",
      build_type: "Release",
    )
    upload_to_play_store(
      release_status: 'completed',
      track: 'beta',
      rollout: '1.0',
      apk: 'app/build/outputs/apk/app/release/app-release.apk',
      skip_upload_images: 'true',
      skip_upload_metadata: 'true',
    )
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(
      task: "assemble",
      build_type: "Release",
    )

    upload_to_play_store(
      release_status: 'completed',
      track: 'beta',
      rollout: '1.0',
      apk: 'app/build/outputs/apk/app/release/app-release.apk',
      skip_upload_images: 'true',
      skip_upload_metadata: 'true',
    )

    upload_to_play_store(
      release_status: 'draft',
      track: 'production',
      apk: 'app/build/outputs/apk/app/release/app-release.apk',
      skip_upload_images: 'true',
      skip_upload_metadata: 'true',
    )
  end
end
