name: android-build

on:
  push:
    tags:
      - '*'

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.3'
          bundler-cache: true
      - name: Fetch tags
        run: git fetch --tags --force
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          running-workflow-name: android-build
          check-name: android-unit-test-release
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Build release APKs
        run: bash .github/scripts/fastlane.sh
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
          KEYSTORE_PASSPHRASE: ${{ secrets.KEYSTORE_PASSPHRASE }}
          KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}
          KEYSTORE_PROPERTIES_PASSPHRASE: ${{ secrets.KEYSTORE_PROPERTIES_PASSPHRASE }}
          SECRETS_PROPERTIES: ${{ secrets.SECRETS_PROPERTIES }}
          SECRETS_PROPERTIES_PASSPHRASE: ${{ secrets.SECRETS_PROPERTIES_PASSPHRASE }}
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
          GOOGLE_SERVICES_PASSPHRASE: ${{ secrets.GOOGLE_SERVICES_PASSPHRASE }}
          PLAYSTORE_SERVICE_ACCOUNT: ${{ secrets.PLAYSTORE_SERVICE_ACCOUNT }}
          PLAYSTORE_SERVICE_ACCOUNT_PASSPHRASE: ${{ secrets.PLAYSTORE_SERVICE_ACCOUNT_PASSPHRASE }}
      - name: Publish PlayStore APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/app/release
      - name: Publish Github APK
        uses: actions/upload-artifact@v4
        with:
          name: app-github-release
          path: app/build/outputs/apk/github/release
      - name: Upload APKs to GitHub Release
        run: |
          files=$(find app/build/outputs/apk/ -type f -name '*.apk')
          gh release upload "${{ github.ref_name }}" $files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
