name: android-unit-test-release
on: 
  push:
    tags:
      - '*'

jobs:
  trigger-version-updater:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Trigger version-updater workflow
      uses: peter-evans/repository-dispatch@v1
      with:
        repository: ${{ github.repository }}
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: version-updater

  android-unit-test-release:
    runs-on: ubuntu-latest
    needs: trigger-version-updater
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Configure properties
      run: bash .github/scripts/setup-config.sh
    - name: Test with Gradle
      run: ./gradlew test
