name: android-unit-test
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  android-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Configure dummy files
        run: |
          mv app/.travic-ci/google-services.json app/google-services.json
          mv app/.travic-ci/secrets app/.config/secrets.properties
      - name: Test with Gradle
        run: ./gradlew test
