name: android-unit-test-release
on: 
  push:
    tags:
      - '*'

jobs:
  trigger-version-updater:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Trigger version-updater workflow
      uses: peter-evans/repository-dispatch@v1
      with:
        repository: ${{ github.repository }}
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: version-updater

  android-unit-test-release:
    runs-on: ubuntu-latest
    needs: trigger-version-updater
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Configure dummy files
      run: |
        mv app/.travic-ci/google-services.json app/google-services.json
        mv app/.travic-ci/secrets app/.config/secrets.properties
    - name: Test with Gradle
      run: ./gradlew test
