name: Android test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Configure dummy files
      run: |
        mv app/.travic-ci/google-services.json app/google-services.json
        mv app/.travic-ci/secrets app/.config/secrets.properties
    - name: Test with Gradle
      run: ./gradlew test
