name: gradle-wrapper-validation
on: [push, pull_request]

jobs:
  gradle-wrapper-validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v3