name: release-drafter

on:
  push:
    branches:
      - 'develop'
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    types: [ opened, reopened, synchronize ]

permissions:
  contents: read

jobs:
  update-draft-release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        id: release_drafter
        with:
          config-name: release-drafter-config.yml
          disable-autolabeler: false
          commitish: develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'develop'
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Configure dummy files
        run: |
          mv app/.travic-ci/google-services.json app/google-services.json
          mv app/.travic-ci/secrets app/.config/secrets.properties

      - name: Extract version
        id: version
        run: echo "${{ steps.release_drafter.outputs.resolved_version }}" > VERSION

      - name: Calculate code
        id: code
        run: |
          IFS='.' read -ra VER <<< "$(cat VERSION)"
          MAJOR=$((VER[0] * 1000000000))
          MINOR=$((VER[1] * 1000000))
          PATCH=$((VER[2] * 1000))
          CODE=$((MAJOR + MINOR + PATCH))
          echo "version=$(cat VERSION)" > gradle/version.properties
          echo "code=$CODE" >> gradle/version.properties
          echo "name=v$(cat VERSION)" >> gradle/version.properties

      - name: Show version
        run: cat gradle/version.properties

      - name: Generate version.json
        run: ./gradlew generateVersions

      - name: Push auto generated version file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "automation: update version.properties"
          branch: platform/update-version-meta-data
          commit_options: '--no-verify --signoff'
          file_pattern: 'gradle/version.properties app/.meta/version.json'
          repository: .
          commit_author: Author <actions@github.com>
          create_branch: true
          push_options: '--force'
          skip_fetch: true